version: '3.8'
services:
  n8n:
    image: n8nio/n8n:${N8N_VERSION}
    container_name: ${N8N_CONTAINER_NAME}
    restart: always
    ports:
      - "${N8N_PORT}:5678"
    environment:
      - DB_TYPE=sqlite
      - N8N_EDITOR_BASE_URL=${N8N_BASE_URL}
      - WEBHOOK_TUNNEL_URL=${N8N_WEBHOOK_URL}
      - N8N_PATH=/
      - N8N_HOST=${N8N_HOST}
      - N8N_RUNNERS_ENABLED=${N8N_RUNNERS}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=${N8N_PERM_ENFORCE}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: