version: '3.8'
services:
  ghost:
    image: ghost:${GHOST_VERSION}
    container_name: ${GHOST_CONTAINER_NAME}
    ports:
      - "${GHOST_PORT}:2368"
    environment:
      url: ${GHOST_URL}
      database__client: ${GHOST_DB_CLIENT}
      database__connection__host: ${GHOST_DB_HOST}
      database__connection__user: ${GHOST_DB_USER}
      database__connection__password: ${GHOST_DB_PASSWORD}
      database__connection__database: ${GHOST_DB_NAME}
      mail__transport: ${MAIL_TRANSPORT}
      mail__from: ${MAIL_FROM}
      mail__options__service: ${MAIL_OPTIONS_SERVICE}
      mail__options__auth__user: ${MAIL_OPTIONS_AUTH_USER}
      mail__options__auth__pass: ${MAIL_OPTIONS_AUTH_PASS}
    volumes:
      - ghost_data:/var/lib/ghost/content

volumes:
  ghost_data: